# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a64a9239b520747b31153c391324030a"
name = "Richsmm"
handle = "Rich_smm"
application_url = "https://richsmm-app-9ae9f88dd6e1.herokuapp.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_customers,read_orders,read_products,write_orders"

[auth]
redirect_urls = [
  "https://richsmm-app-9ae9f88dd6e1.herokuapp.com/auth/callback",
  "https://richsmm-app-9ae9f88dd6e1.herokuapp.com/auth/shopify/callback",
  "https://richsmm-app-9ae9f88dd6e1.herokuapp.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false

[build]
dev_store_url = "smmstoretest.myshopify.com"
automatically_update_urls_on_dev = true
