# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a64a9239b520747b31153c391324030a"
application_url = "https://aus-ds-philips-fellow.trycloudflare.com"
embedded = true
name = "Richsmm"
handle = "rich_smm"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "smmstoretest.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://corruption-bathrooms-alpha-completion.trycloudflare.com/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_orders,write_products"

[auth]
redirect_urls = [
  "https://aus-ds-philips-fellow.trycloudflare.com/auth/callback",
  "https://aus-ds-philips-fellow.trycloudflare.com/auth/shopify/callback",
  "https://aus-ds-philips-fellow.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
